# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2016, 7, 5, 19, 36, 1, 234736, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2016, 7, 5, 19, 36, 1, 235444, tzinfo=utc))),
                ('occupation', models.CharField(max_length=200)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.Interest')),
            ],
        ),
    ]
